### ISSUE TITLE
Using follow with a String creates a ClassCastException

### ISSUE THREAD

**Issue by Kungi** [xeqi/kerodon#32]
I am using the current 0.6.0-SNAPSHOT release.

When I use `(kerodon.core/follow "Logout")` I get the following exception:

I also created a pastebin http://pastebin.com/dzQQu5ts with the testing code, the stacktrace and the current state.

       1. Unhandled java.lang.ClassCastException
        clojure.lang.PersistentStructMap cannot be cast to java.lang.CharSequence
     
        string.clj:  236  clojure.string/trim
        core.clj: 2557  clojure.core/map/fn
                      LazySeq.java:   40  clojure.lang.LazySeq/sval
       LazySeq.java:   49  clojure.lang.LazySeq/seq
        LazySeq.java:  115  clojure.lang.LazySeq/equals
        LazySeq.java:  100  clojure.lang.LazySeq/equiv
        Util.java:  124  clojure.lang.Util/pcequiv
        Util.java:   32  clojure.lang.Util/equiv
        impl.clj:   30  kerodon.impl/css-or-content/fn
        enlive_html.clj:  241  net.cgrand.enlive-html/pred/fn
        enlive_html.clj:  236  net.cgrand.enlive-html/zip-pred/fn
        enlive_html.clj:  282  net.cgrand.enlive-html/intersection/fn
        enlive_html.clj:  329  net.cgrand.enlive-html/predset/fn
        core.clj: 2403  clojure.core/comp/fn
        enlive_html.clj:  390  net.cgrand.enlive-html/step
        enlive_html.clj:  497  net.cgrand.enlive-html/zip-select-nodes*/select1
                   enlive_html.clj:  498  net.cgrand.enlive-html/zip-select-nodes*/select1/fn
       core.clj: 2559  clojure.core/map/fn
                      LazySeq.java:   40  clojure.lang.LazySeq/sval
       LazySeq.java:   49  clojure.lang.LazySeq/seq
        RT.java:  484  clojure.lang.RT/seq
        core.clj:  133  clojure.core/seq
        core.clj:  624  clojure.core/apply
        core.clj: 2586  clojure.core/mapcat
        RestFn.java:  423  clojure.lang.RestFn/invoke
        enlive_html.clj:  498  net.cgrand.enlive-html/zip-select-nodes*/select1
                   enlive_html.clj:  498  net.cgrand.enlive-html/zip-select-nodes*/select1/fn
       core.clj: 2559  clojure.core/map/fn
                      LazySeq.java:   40  clojure.lang.LazySeq/sval
       LazySeq.java:   49  clojure.lang.LazySeq/seq
        RT.java:  484  clojure.lang.RT/seq
        core.clj:  133  clojure.core/seq
        core.clj:  624  clojure.core/apply
        core.clj: 2586  clojure.core/mapcat
        RestFn.java:  423  clojure.lang.RestFn/invoke
        enlive_html.clj:  498  net.cgrand.enlive-html/zip-select-nodes*/select1
                   enlive_html.clj:  498  net.cgrand.enlive-html/zip-select-nodes*/select1/fn
       core.clj: 2559  clojure.core/map/fn
                      LazySeq.java:   40  clojure.lang.LazySeq/sval
       LazySeq.java:   49  clojure.lang.LazySeq/seq
        RT.java:  484  clojure.lang.RT/seq
        core.clj:  133  clojure.core/seq
        core.clj:  624  clojure.core/apply
        core.clj: 2586  clojure.core/mapcat
        RestFn.java:  423  clojure.lang.RestFn/invoke
        enlive_html.clj:  498  net.cgrand.enlive-html/zip-select-nodes*/select1
                   enlive_html.clj:  498  net.cgrand.enlive-html/zip-select-nodes*/select1/fn
       core.clj: 2559  clojure.core/map/fn
                      LazySeq.java:   40  clojure.lang.LazySeq/sval
       LazySeq.java:   49  clojure.lang.LazySeq/seq
        Cons.java:   39  clojure.lang.Cons/next
        RT.java: 1654  clojure.lang.RT/boundedLength
        RestFn.java:  130  clojure.lang.RestFn/applyTo
        core.clj:  624  clojure.core/apply
        core.clj: 2586  clojure.core/mapcat
        RestFn.java:  423  clojure.lang.RestFn/invoke
        enlive_html.clj:  498  net.cgrand.enlive-html/zip-select-nodes*/select1
                   enlive_html.clj:  498  net.cgrand.enlive-html/zip-select-nodes*/select1/fn
       core.clj: 2559  clojure.core/map/fn
                      LazySeq.java:   40  clojure.lang.LazySeq/sval
       LazySeq.java:   49  clojure.lang.LazySeq/seq
        RT.java:  484  clojure.lang.RT/seq
        core.clj:  133  clojure.core/seq
        core.clj:  624  clojure.core/apply
        core.clj: 2586  clojure.core/mapcat
        RestFn.java:  423  clojure.lang.RestFn/invoke
        enlive_html.clj:  498  net.cgrand.enlive-html/zip-select-nodes*/select1
                   enlive_html.clj:  498  net.cgrand.enlive-html/zip-select-nodes*/select1/fn
       core.clj: 2559  clojure.core/map/fn
                      LazySeq.java:   40  clojure.lang.LazySeq/sval
       LazySeq.java:   49  clojure.lang.LazySeq/seq
        Cons.java:   39  clojure.lang.Cons/next
        RT.java: 1654  clojure.lang.RT/boundedLength
        RestFn.java:  130  clojure.lang.RestFn/applyTo
        core.clj:  624  clojure.core/apply
        core.clj: 2586  clojure.core/mapcat
        RestFn.java:  423  clojure.lang.RestFn/invoke
        enlive_html.clj:  498  net.cgrand.enlive-html/zip-select-nodes*/select1
                   enlive_html.clj:  498  net.cgrand.enlive-html/zip-select-nodes*/select1/fn
       core.clj: 2559  clojure.core/map/fn
                      LazySeq.java:   40  clojure.lang.LazySeq/sval
       LazySeq.java:   49  clojure.lang.LazySeq/seq
        Cons.java:   39  clojure.lang.Cons/next
        RT.java: 1654  clojure.lang.RT/boundedLength
        RestFn.java:  130  clojure.lang.RestFn/applyTo
        core.clj:  624  clojure.core/apply
        core.clj: 2586  clojure.core/mapcat
        RestFn.java:  423  clojure.lang.RestFn/invoke
        enlive_html.clj:  498  net.cgrand.enlive-html/zip-select-nodes*/select1
                   enlive_html.clj:  498  net.cgrand.enlive-html/zip-select-nodes*/select1/fn
       core.clj: 2559  clojure.core/map/fn
                      LazySeq.java:   40  clojure.lang.LazySeq/sval
       LazySeq.java:   49  clojure.lang.LazySeq/seq
        Cons.java:   39  clojure.lang.Cons/next
        RT.java: 1654  clojure.lang.RT/boundedLength
        RestFn.java:  130  clojure.lang.RestFn/applyTo
        core.clj:  624  clojure.core/apply
        core.clj: 2586  clojure.core/mapcat
        RestFn.java:  423  clojure.lang.RestFn/invoke
        enlive_html.clj:  498  net.cgrand.enlive-html/zip-select-nodes*/select1
                   enlive_html.clj:  500  net.cgrand.enlive-html/zip-select-nodes*/fn
                          core.clj: 2559  clojure.core/map/fn
                      LazySeq.java:   40  clojure.lang.LazySeq/sval
       LazySeq.java:   49  clojure.lang.LazySeq/seq
        RT.java:  484  clojure.lang.RT/seq
        core.clj:  133  clojure.core/seq
        core.clj:  624  clojure.core/apply
        core.clj: 2586  clojure.core/mapcat
        RestFn.java:  423  clojure.lang.RestFn/invoke
        enlive_html.clj:  500  net.cgrand.enlive-html/zip-select-nodes*
        enlive_html.clj:  504  net.cgrand.enlive-html/select-nodes*
        enlive_html.clj:  543  net.cgrand.enlive-html/select
        impl.clj:   83  kerodon.impl/link
        impl.clj:  213  kerodon.impl/find-url
        core.clj:   19  kerodon.core/follow
        acceptance_test.clj:   66  web.acceptance-test/fn
        test.clj:  704  clojure.test/test-var/fn
        test.clj:  704  clojure.test/test-var
        test.clj:  124  cider.nrepl.middleware.test/test-vars/fn/fn
        test_data.clj:  215  clj-demgen.test-data/with-test-data
        test.clj:  681  clojure.test/compose-fixtures/fn/fn
        acceptance_test.clj:   23  web.acceptance-test/with-test-system
        test.clj:  681  clojure.test/compose-fixtures/fn/fn
        test.clj:  674  clojure.test/default-fixture
        test.clj:  681  clojure.test/compose-fixtures/fn
        test.clj:  681  clojure.test/compose-fixtures/fn
        test.clj:  124  cider.nrepl.middleware.test/test-vars/fn
        test_data.clj:   29  clj-demgen.test-data/with-test-home-folder
        test.clj:  681  clojure.test/compose-fixtures/fn/fn
        test.clj:  674  clojure.test/default-fixture
        test.clj:  681  clojure.test/compose-fixtures/fn
        test.clj:  120  cider.nrepl.middleware.test/test-vars
        test.clj:  139  cider.nrepl.middleware.test/test-ns
        test.clj:  161  cider.nrepl.middleware.test/handle-test/fn
        AFn.java:  152  clojure.lang.AFn/applyToHelper
        AFn.java:  144  clojure.lang.AFn/applyTo
        core.clj:  624  clojure.core/apply
        core.clj: 1862  clojure.core/with-bindings*
        RestFn.java:  425  clojure.lang.RestFn/invoke
        test.clj:  159  cider.nrepl.middleware.test/handle-test
        test.clj:  200  cider.nrepl.middleware.test/wrap-test/fn

Using `(kerodon.core/follow :#id-of-logout-link)` works fine btw. The link is present on the page.

**Comment by thegeez** [comment]
A workaround is to use:

```(kerodon.core/follow (net.cgrand.enlive-html/pred #(= (first (:content %)) "Logout")))```
