### ISSUE TITLE
Trouble with GET params and `follow-redirect`

### ISSUE THREAD

**Issue by EuAndreh** [xeqi/kerodon#35]
Hi there.

I'm having problem with GET params in the URI. When testing the app with `visit`, the app doesn't receive the GET params:
```Clojure
(-> (session app)
      (visit "/guy" :params {"key" "guyskey"}))
;; or the equivalent
(-> (session app)
      (visit "/guy?key=guyskey"))
```
In both cases the `:query-string` is `"key=guyskey"`, but the app doesn't receive those values.

I also get this error when using follow redirect:
```clojure
(deftest site-navegation-test
  (-> (session app)
      (visit "/")
      (fill-in :#key "André")
      (press "Buscar atleta")
      (follow-redirect)))
Uncaught exception, not in assertion.
expected: nil
  actual: java.lang.IllegalArgumentException: Previous response was not a redirect
 at peridot.core$follow_redirect.invoke (core.clj:59)
    kerodon.core$follow_redirect.invoke (core.clj:16)
...
```

Is there anything I'm doing wrong?

**Comment by glenjamin** [comment]
It looks like you might be missing query string parsing middleware.

I'm not sure what's up with the redirect, I'd need to see the app code to advise further.

**Comment by EuAndreh** [comment]
The app is [EuAndreh/sem-nome-tro](http://github/EuAndreh/sem-nome-tro), and the test is `navegação-pelo-site`.

The error message is `Previous response was not a redirect` instead of `button could not be found with selector "Buscar atleta"`, which means that the `(press "Buscar atleta")` is actually doing its job.

What am I missing?

Thank you very much for the help.

**Comment by glenjamin** [comment]
The page you linked does not return a redirect (HTTP 301/302) response.

The form submits to `/atleta`, which returns a normal page.

**Comment by EuAndreh** [comment]
Thanks, I now realize what I'm missing.

Thanks for the support.
