### ISSUE TITLE
Add support for labels that don't have for attributes

### ISSUE THREAD

**Issue by danielflower** [xeqi/kerodon#36]
Although it appears that [this commit](https://github.com/xeqi/kerodon/commit/1bf1c8c5e2b3003b12a035fbc6cd128f6d3580af) added support for `for`-less labels, it's not working for me on version 0.5.0.

Does not work:

    <label>Username
        <input id="username" type="text" autocomplete="nickname" name="username" autofocus required maxlength="50" value="{{username}}">
    </label>

Does work:

    <label for="username">Username</label>
    <input id="username" type="text" autocomplete="nickname" name="username" autofocus required maxlength="50" value="{{username}}">

**Comment by glenjamin** [comment]
Hrm, that doesn't look different to the test case that passes.

Can you try `<label>Username<input`? It might be a whitespace issue.

If this fixes it, we can add a whitespace trim into the css-or-label function.

**Comment by danielflower** [comment]
Yeah, I tried that already, with no whitespace either side of the `input` tag, but it still didn't work. Slight typo in my original post though - I'm using 0.6.0-SNAPSHOT rather than 0.5.0

**Comment by danielflower** [comment]
Sorry, I take that back. Just tried again and it was indeed whitespace causing the issue. Personally, I think trimming the string would be good though.

**Comment by glenjamin** [comment]
Yep, I'll add that when I get a chance - or a PR is welcome :)

**Comment by danielflower** [comment]
Thanks man, and thanks for the useful project. I've just started using it and have had a good experience so far.
