### ISSUE TITLE
Browser-like treatment of whitespace in text

### ISSUE THREAD

**Issue by garycrawford** [xeqi/kerodon#37]
Hi,
Thanks for all of your great work - I'm finding Kerodon really useful!

I just wondered if you have any plans to push a version to Clojars in the near future? The "Browser-like treatment of whitespace in text" in particular is something I'm really to get my hands on.

thanks
Gary

**Comment by glenjamin** [comment]
I'll try and push something out tonight

**Comment by garycrawford** [comment]
That's fantastic - thank you for the fast response!

... would you happen to be the Glen that was at EuroClojure last year?

**Comment by glenjamin** [comment]
Yep, that's me - I'll be at this year's too.

**Comment by garycrawford** [comment]
Cool, me to. I think we had a few beers together one night last year in the evening market in Krakow. Someone was going round the tables asking people to buy him a guitar if I remember correctly!

**Comment by glenjamin** [comment]
I remember that!

Also, https://clojars.org/kerodon/versions/0.6.0 is now available.

**Comment by garycrawford** [comment]
Fantastic, thank you for such a fast response!

See you at EC :-)
