### ISSUE TITLE
Exception when any a tag contains other tags

### ISSUE THREAD

**Issue by danielflower** [xeqi/kerodon#38]
If there are any `<a>` tags that contain other HTML tags like images or spans, then an error is thrown.

Okay:

    <a href="/">Home</a>

Error:

    <a href="/"><span>Home</span></a>

Note the error occurs when `(follow "whatever")` is used.

	ERROR in (swirl-security) (string.clj:236)
	Uncaught exception, not in assertion.
	expected: nil
	  actual: java.lang.ClassCastException: clojure.lang.PersistentStructMap cannot be cast to java.lang.CharSequence
	 at clojure.string$trim.invoke (string.clj:236)
		clojure.core$map$fn__4245.invoke (core.clj:2559)
		clojure.lang.LazySeq.sval (LazySeq.java:40)
		clojure.lang.LazySeq.seq (LazySeq.java:49)
		clojure.lang.LazySeq.equals (LazySeq.java:115)
		clojure.lang.LazySeq.equiv (LazySeq.java:100)
		clojure.lang.Util.pcequiv (Util.java:124)
		clojure.lang.Util.equiv (Util.java:32)
		kerodon.impl$css_or_content$fn__16846.invoke (impl.clj:30)
		net.cgrand.enlive_html$pred$fn__16009.invoke (enlive_html.clj:241)
		net.cgrand.enlive_html$zip_pred$fn__16004.invoke (enlive_html.clj:236)
		net.cgrand.enlive_html$intersection$fn__16043.invoke (enlive_html.clj:282)
		net.cgrand.enlive_html$predset$fn__16137.invoke (enlive_html.clj:329)
		clojure.core$comp$fn__4192.invoke (core.clj:2403)
		net.cgrand.enlive_html$step.invoke (enlive_html.clj:390)
		net.cgrand.enlive_html$zip_select_nodes_STAR_$select1__16290.invoke (enlive_html.clj:497)
		net.cgrand.enlive_html$zip_select_nodes_STAR_$select1__16290$fn__16291.invoke (enlive_html.clj:498)
		clojure.core$map$fn__4245.invoke (core.clj:2559)
		clojure.lang.LazySeq.sval (LazySeq.java:40)
		clojure.lang.LazySeq.seq (LazySeq.java:49)
		clojure.lang.Cons.next (Cons.java:39)
		clojure.lang.RT.boundedLength (RT.java:1654)
		clojure.lang.RestFn.applyTo (RestFn.java:130)
		clojure.core$apply.invoke (core.clj:624)
		clojure.core$mapcat.doInvoke (core.clj:2586)
		clojure.lang.RestFn.invoke (RestFn.java:423)
		net.cgrand.enlive_html$zip_select_nodes_STAR_$select1__16290.invoke (enlive_html.clj:498)
		net.cgrand.enlive_html$zip_select_nodes_STAR_$select1__16290$fn__16291.invoke (enlive_html.clj:498)
		clojure.core$map$fn__4245.invoke (core.clj:2559)
		clojure.lang.LazySeq.sval (LazySeq.java:40)
		clojure.lang.LazySeq.seq (LazySeq.java:49)
		clojure.lang.Cons.next (Cons.java:39)
		clojure.lang.RT.boundedLength (RT.java:1654)
		clojure.lang.RestFn.applyTo (RestFn.java:130)
		clojure.core$apply.invoke (core.clj:624)
		clojure.core$mapcat.doInvoke (core.clj:2586)
		clojure.lang.RestFn.invoke (RestFn.java:423)
		net.cgrand.enlive_html$zip_select_nodes_STAR_$select1__16290.invoke (enlive_html.clj:498)
		net.cgrand.enlive_html$zip_select_nodes_STAR_$select1__16290$fn__16291.invoke (enlive_html.clj:498)
		clojure.core$map$fn__4245.invoke (core.clj:2559)
		clojure.lang.LazySeq.sval (LazySeq.java:40)
		clojure.lang.LazySeq.seq (LazySeq.java:49)
		clojure.lang.Cons.next (Cons.java:39)
		clojure.lang.RT.boundedLength (RT.java:1654)
		clojure.lang.RestFn.applyTo (RestFn.java:130)
		clojure.core$apply.invoke (core.clj:624)
		clojure.core$mapcat.doInvoke (core.clj:2586)
		clojure.lang.RestFn.invoke (RestFn.java:423)
		net.cgrand.enlive_html$zip_select_nodes_STAR_$select1__16290.invoke (enlive_html.clj:498)
		net.cgrand.enlive_html$zip_select_nodes_STAR_$select1__16290$fn__16291.invoke (enlive_html.clj:498)
		clojure.core$map$fn__4245.invoke (core.clj:2559)
		clojure.lang.LazySeq.sval (LazySeq.java:40)
		clojure.lang.LazySeq.seq (LazySeq.java:49)
		clojure.lang.Cons.next (Cons.java:39)
		clojure.lang.RT.boundedLength (RT.java:1654)
		clojure.lang.RestFn.applyTo (RestFn.java:130)
		clojure.core$apply.invoke (core.clj:624)
		clojure.core$mapcat.doInvoke (core.clj:2586)
		clojure.lang.RestFn.invoke (RestFn.java:423)
		net.cgrand.enlive_html$zip_select_nodes_STAR_$select1__16290.invoke (enlive_html.clj:498)
		net.cgrand.enlive_html$zip_select_nodes_STAR_$select1__16290$fn__16291.invoke (enlive_html.clj:498)
		clojure.core$map$fn__4245.invoke (core.clj:2559)
		clojure.lang.LazySeq.sval (LazySeq.java:40)
		clojure.lang.LazySeq.seq (LazySeq.java:49)
		clojure.lang.Cons.next (Cons.java:39)
		clojure.lang.RT.boundedLength (RT.java:1654)
		clojure.lang.RestFn.applyTo (RestFn.java:130)
		clojure.core$apply.invoke (core.clj:624)
		clojure.core$mapcat.doInvoke (core.clj:2586)
		clojure.lang.RestFn.invoke (RestFn.java:423)
		net.cgrand.enlive_html$zip_select_nodes_STAR_$select1__16290.invoke (enlive_html.clj:498)
		net.cgrand.enlive_html$zip_select_nodes_STAR_$select1__16290$fn__16291.invoke (enlive_html.clj:498)
		clojure.core$map$fn__4245.invoke (core.clj:2559)
		clojure.lang.LazySeq.sval (LazySeq.java:40)
		clojure.lang.LazySeq.seq (LazySeq.java:49)
		clojure.lang.Cons.next (Cons.java:39)
		clojure.lang.RT.boundedLength (RT.java:1654)
		clojure.lang.RestFn.applyTo (RestFn.java:130)
		clojure.core$apply.invoke (core.clj:624)
		clojure.core$mapcat.doInvoke (core.clj:2586)
		clojure.lang.RestFn.invoke (RestFn.java:423)
		net.cgrand.enlive_html$zip_select_nodes_STAR_$select1__16290.invoke (enlive_html.clj:498)
		net.cgrand.enlive_html$zip_select_nodes_STAR_$fn__16295.invoke (enlive_html.clj:500)
		clojure.core$map$fn__4245.invoke (core.clj:2559)
		clojure.lang.LazySeq.sval (LazySeq.java:40)
		clojure.lang.LazySeq.seq (LazySeq.java:49)
		clojure.lang.RT.seq (RT.java:484)
		clojure.core$seq.invoke (core.clj:133)
		clojure.core$apply.invoke (core.clj:624)
		clojure.core$mapcat.doInvoke (core.clj:2586)
		clojure.lang.RestFn.invoke (RestFn.java:423)
		net.cgrand.enlive_html$zip_select_nodes_STAR_.invoke (enlive_html.clj:500)
		net.cgrand.enlive_html$select_nodes_STAR_.invoke (enlive_html.clj:504)
		net.cgrand.enlive_html$select.invoke (enlive_html.clj:543)
		kerodon.impl$link.invoke (impl.clj:83)
		kerodon.impl$find_url.invoke (impl.clj:213)
		kerodon.core$follow.invoke (core.clj:19)
		yswrl.features.swirl_features/fn (swirl_features.clj:52)
		clojure.test$test_var$fn__7187.invoke (test.clj:704)
		clojure.test$test_var.invoke (test.clj:704)
		clojure.test$test_vars$fn__7209$fn__7214.invoke (test.clj:722)
		clojure.test$default_fixture.invoke (test.clj:674)
		clojure.test$test_vars$fn__7209.invoke (test.clj:722)
		clojure.test$default_fixture.invoke (test.clj:674)
		clojure.test$test_vars.invoke (test.clj:718)
		clojure.test$test_all_vars.invoke (test.clj:728)
		clojure.test$test_ns.invoke (test.clj:747)
		clojure.core$map$fn__4245.invoke (core.clj:2559)
		clojure.lang.LazySeq.sval (LazySeq.java:40)
		clojure.lang.LazySeq.seq (LazySeq.java:49)
		clojure.lang.Cons.next (Cons.java:39)
		clojure.lang.RT.next (RT.java:598)
		clojure.core$next.invoke (core.clj:64)
		clojure.core$reduce1.invoke (core.clj:903)
		clojure.core$reduce1.invoke (core.clj:894)
		clojure.core$merge_with.doInvoke (core.clj:2777)
		clojure.lang.RestFn.applyTo (RestFn.java:139)
		clojure.core$apply.invoke (core.clj:626)
		clojure.test$run_tests.doInvoke (test.clj:762)
		clojure.lang.RestFn.applyTo (RestFn.java:137)
		clojure.core$apply.invoke (core.clj:624)
		com.jakemccrary.test_refresh$run_selected_tests$fn__656.invoke (test_refresh.clj:129)
		com.jakemccrary.test_refresh$suppress_unselected_tests.invoke (test_refresh.clj:103)
		com.jakemccrary.test_refresh$run_selected_tests.invoke (test_refresh.clj:127)
		com.jakemccrary.test_refresh$run_tests.invoke (test_refresh.clj:135)
		com.jakemccrary.test_refresh$monitor_project$fn__672.invoke (test_refresh.clj:192)
		com.jakemccrary.test_refresh$monitor_project.invoke (test_refresh.clj:185)
		user$eval730.invoke (form-init5254813364040845940.clj:1)
		clojure.lang.Compiler.eval (Compiler.java:6703)
		clojure.lang.Compiler.eval (Compiler.java:6693)
		clojure.lang.Compiler.load (Compiler.java:7130)
		clojure.lang.Compiler.loadFile (Compiler.java:7086)
		clojure.main$load_script.invoke (main.clj:274)
		clojure.main$init_opt.invoke (main.clj:279)
		clojure.main$initialize.invoke (main.clj:307)
		clojure.main$null_opt.invoke (main.clj:342)
		clojure.main$main.doInvoke (main.clj:420)
		clojure.lang.RestFn.invoke (RestFn.java:421)
		clojure.lang.Var.invoke (Var.java:383)
		clojure.lang.AFn.applyToHelper (AFn.java:156)
		clojure.lang.Var.applyTo (Var.java:700)
		clojure.main.main (main.java:37)

**Comment by glenjamin** [comment]
Unsure when i'll have time to work on this, but I'll gladly take PRs.

The link matcher just needs to extract the whole text content of the `<a>` via enlive, instead of assuming the node content will be a string.

**Comment by danielflower** [comment]
Sorry, my mistake. Was fixed in 0.6.0 by the commit that added trimming to all the strings.
